fix typo of build-in-type file name for UInt8
*CAUSE:*
$ bash build.sh
<snipped>
[1962/2480] Building CXX object CMakeFiles/battery_monitor.dir/mros2/src/mros2.cpp.obj
<snipped>
FAILED: CMakeFiles/battery_monitor.dir/mros2/src/mros2.cpp.obj
In file included from /var/mbed/mros2/src/mros2.cpp:280:
/var/mbed/battery_monitor/templates.hpp:1:10: fatal error: std_msgs/msg/u_int18.hpp: No such file or directory
    1 | #include "std_msgs/msg/u_int18.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[1969/2480] Building CXX object CMakeFiles/...G96/QUECTEL_BG96_ControlPlane_netif.cpp.obj
In file included from /var/mbed/mbed-os/connectivity/cellular/./include/cellular/framework/AT/AT_ControlPlane_netif.h:21,
                 from /var/mbed/mbed-os/connectivity/drivers/cellular/QUECTEL/BG96/QUECTEL_BG96_ControlPlane_netif.h:20,
                 from /var/mbed/mbed-os/connectivity/drivers/cellular/QUECTEL/BG96/QUECTEL_BG96_ControlPlane_netif.cpp:19:
/var/mbed/mbed-os/connectivity/cellular/./include/cellular/framework/AT/AT_CellularDevice.h:70:53: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   70 |     AT_CellularDevice(FileHandle *fh, char *delim = "\r");
      |                                                     ^~~~
[1971/2480] Building CXX object CMakeFiles/...TEL/BG96/QUECTEL_BG96_CellularStack.cpp.obj
In file included from /var/mbed/mbed-os/connectivity/cellular/./include/cellular/framework/AT/AT_CellularStack.h:24,
                 from /var/mbed/mbed-os/connectivity/drivers/cellular/./QUECTEL/BG96/QUECTEL_BG96_CellularStack.h:21,
                 from /var/mbed/mbed-os/connectivity/drivers/cellular/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp:20:
/var/mbed/mbed-os/connectivity/cellular/./include/cellular/framework/AT/AT_CellularDevice.h:70:53: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   70 |     AT_CellularDevice(FileHandle *fh, char *delim = "\r");
      |                                                     ^~~~
ninja: build stopped: subcommand failed.
ERROR: CMake invocation failed!

*WHY:*
Typo of the file name about build-in-type UInt8. The correct file name is "u_int8.hpp"

*HOW to FIX:*
Fix typo in the file name.