add include path to the app's dir
*CAUSE:*
$ bash build.sh
<snipped>
[2479/2480] Building CXX object CMakeFiles/battery_monitor.dir/mros2/src/mros2.cpp.obj
<snipped>
FAILED: CMakeFiles/battery_monitor.dir/mros2/src/mros2.cpp.obj
/var/mbed/mros2/src/mros2.cpp:280:10: fatal error: templates.hpp: No such file or directory
  280 | #include "templates.hpp"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
ERROR: CMake invocation failed!

*WHY:*
Building mros2.cpp requires include path to the app's dir for `#include "templates.hpp"`. This file is expected to be described the template functions that are used in the application.
https://github.com/mROS-base/mros2/blob/main/src/mros2.cpp#L277-L280

*HOW to FIX:*
add `include_directories(APP_DIR)` in CMakeLists.txt